export const products = [
    { id: 1, name: "Classic Keyring - Letter A", category: "keyrings", price: 3.99, description: "Personalised letter keyring in durable PLA" },
    { id: 2, name: "Classic Keyring - Letter B", category: "keyrings", price: 3.99, description: "Personalised letter keyring in durable PLA" },
    { id: 3, name: "Classic Keyring - Letter C", category: "keyrings", price: 3.99, description: "Personalised letter keyring in durable PLA" },
    { id: 4, name: "Classic Keyring - Letter D", category: "keyrings", price: 3.99, description: "Personalised letter keyring in durable PLA" },
    { id: 5, name: "Classic Keyring - Letter E", category: "keyrings", price: 3.99, description: "Personalised letter keyring in durable PLA" },
    { id: 6, name: "Heart Shape Keyring", category: "keyrings", price: 4.49, description: "Lovely heart-shaped keyring, perfect gift" },
    { id: 7, name: "Star Shape Keyring", category: "keyrings", price: 4.49, description: "Five-pointed star keyring in vibrant colours" },
    { id: 8, name: "Circle Keyring - Plain", category: "keyrings", price: 3.49, description: "Simple circular keyring, minimalist design" },
    { id: 9, name: "Hexagon Keyring", category: "keyrings", price: 4.99, description: "Geometric hexagon keyring, modern style" },
    { id: 10, name: "Custom Name Keyring", category: "keyrings", price: 5.99, description: "Personalised with your name or text" },
    { id: 11, name: "House Shape Keyring", category: "keyrings", price: 4.99, description: "Cute house-shaped keyring for home keys" },
    { id: 12, name: "Car Shape Keyring", category: "keyrings", price: 4.99, description: "Miniature car keyring for vehicle keys" },
    { id: 13, name: "Dog Paw Keyring", category: "keyrings", price: 4.49, description: "Perfect for dog lovers, paw print design" },
    { id: 14, name: "Cat Silhouette Keyring", category: "keyrings", price: 4.49, description: "Elegant cat shape keyring for cat owners" },
    { id: 15, name: "Music Note Keyring", category: "keyrings", price: 4.49, description: "Musical note design for music enthusiasts" },
    { id: 16, name: "Football Keyring", category: "keyrings", price: 4.49, description: "Mini football keyring for sports fans" },
    { id: 17, name: "Crown Keyring", category: "keyrings", price: 5.49, description: "Royal crown design, premium finish" },
    { id: 18, name: "Anchor Keyring", category: "keyrings", price: 4.99, description: "Nautical anchor design keyring" },
    { id: 19, name: "Rainbow Keyring", category: "keyrings", price: 5.99, description: "Colourful rainbow arc keyring" },
    { id: 20, name: "Lightning Bolt Keyring", category: "keyrings", price: 4.49, description: "Electric lightning bolt design" },

    { id: 21, name: "Articulated Dragon", category: "models", price: 12.99, description: "Fully articulated dragon figure, moveable joints" },
    { id: 22, name: "Celtic Cross Model", category: "models", price: 9.99, description: "Intricate Celtic cross decorative piece" },
    { id: 23, name: "Geometric Sphere", category: "models", price: 8.99, description: "Mathematical sphere with geodesic pattern" },
    { id: 24, name: "Low Poly Bear", category: "models", price: 11.99, description: "Modern low-poly bear sculpture" },
    { id: 25, name: "Low Poly Fox", category: "models", price: 11.99, description: "Geometric fox model, minimalist art" },
    { id: 26, name: "Skull Model - Full Size", category: "models", price: 15.99, description: "Anatomically accurate skull model" },
    { id: 27, name: "Mandala Wall Art", category: "models", price: 14.99, description: "Intricate mandala design for wall mounting" },
    { id: 28, name: "Voronoi Vase", category: "models", price: 13.99, description: "Organic voronoi pattern vase" },
    { id: 29, name: "Spiral Tower Model", category: "models", price: 10.99, description: "Twisting spiral tower sculpture" },
    { id: 30, name: "Flexi Rex Dinosaur", category: "models", price: 14.99, description: "Flexible T-Rex with articulated body" },
    { id: 31, name: "Crystal Geometric Lamp", category: "models", price: 18.99, description: "Geometric lamp shade, LED compatible" },
    { id: 32, name: "Octopus Figurine", category: "models", price: 12.99, description: "Detailed octopus model with tentacles" },
    { id: 33, name: "Moon Lithophane", category: "models", price: 16.99, description: "3D moon with backlit detail" },
    { id: 34, name: "Eiffel Tower Replica", category: "models", price: 9.99, description: "Miniature Eiffel Tower model" },
    { id: 35, name: "Chess Set - Complete", category: "models", price: 24.99, description: "Full chess set with 32 pieces" },
    { id: 36, name: "Viking Ship Model", category: "models", price: 17.99, description: "Detailed Viking longship replica" },
    { id: 37, name: "Greek Temple Model", category: "models", price: 19.99, description: "Classical Greek temple architecture" },
    { id: 38, name: "Zen Garden Set", category: "models", price: 13.99, description: "Miniature zen garden decorative set" },
    { id: 39, name: "Owl Figurine", category: "models", price: 11.99, description: "Wise owl decorative figure" },
    { id: 40, name: "Abstract Face Art", category: "models", price: 14.99, description: "Modern abstract face sculpture" },

    { id: 41, name: "Laptop Stand - Ergonomic", category: "parts", price: 11.99, description: "Adjustable laptop stand for better posture" },
    { id: 42, name: "Cable Organiser - Desk", category: "parts", price: 4.99, description: "Keep cables tidy on your desk" },
    { id: 43, name: "Phone Stand - Adjustable", category: "parts", price: 6.99, description: "Universal phone holder with angle adjustment" },
    { id: 44, name: "Drawer Dividers - Set of 4", category: "parts", price: 8.99, description: "Customisable drawer organisation system" },
    { id: 45, name: "Headphone Holder - Wall Mount", category: "parts", price: 5.99, description: "Wall-mounted headphone hanger" },
    { id: 46, name: "Replacement Knobs - Set of 6", category: "parts", price: 7.99, description: "Universal replacement knobs for furniture" },
    { id: 47, name: "Curtain Rail Brackets", category: "parts", price: 6.49, description: "Strong curtain rail support brackets" },
    { id: 48, name: "Camera Tripod Mount", category: "parts", price: 9.99, description: "Universal camera mounting adapter" },
    { id: 49, name: "Tablet Stand - Desktop", category: "parts", price: 8.99, description: "Stable tablet holder for desk use" },
    { id: 50, name: "Pen Holder - Multi Slot", category: "parts", price: 5.49, description: "Desk organiser for pens and pencils" },
    { id: 51, name: "Monitor Stand Riser", category: "parts", price: 12.99, description: "Raise monitor to eye level with storage" },
    { id: 52, name: "Keyboard Feet Replacement", category: "parts", price: 3.99, description: "Universal keyboard feet set of 4" },
    { id: 53, name: "Soap Dish - Drainage", category: "parts", price: 4.49, description: "Bathroom soap dish with drainage holes" },
    { id: 54, name: "Toothbrush Holder - Wall", category: "parts", price: 5.99, description: "Space-saving wall-mounted holder" },
    { id: 55, name: "Coat Hook - Single", category: "parts", price: 3.49, description: "Strong wall-mounted coat hook" },
    { id: 56, name: "Picture Frame Corner", category: "parts", price: 2.99, description: "Replacement frame corner brackets" },
    { id: 57, name: "Door Stop - Heavy Duty", category: "parts", price: 4.99, description: "Robust door stopper with rubber base" },
    { id: 58, name: "Shelf Bracket - L Shape", category: "parts", price: 6.99, description: "Strong L-shaped shelf support" },
    { id: 59, name: "Plant Pot Feet - Set of 3", category: "parts", price: 5.49, description: "Raise pots for drainage and airflow" },
    { id: 60, name: "Vacuum Attachment Holder", category: "parts", price: 7.99, description: "Wall storage for vacuum accessories" },

    { id: 61, name: "Measuring Scoop Set", category: "tools", price: 6.99, description: "Precision measuring scoops for cooking" },
    { id: 62, name: "Funnel - Wide Mouth", category: "tools", price: 4.49, description: "Kitchen funnel for easy pouring" },
    { id: 63, name: "Scraper Tool", category: "tools", price: 3.99, description: "Versatile scraping tool for various uses" },
    { id: 64, name: "Bottle Opener", category: "tools", price: 4.99, description: "Ergonomic bottle opener with grip" },
    { id: 65, name: "Cord Wrapper", category: "tools", price: 3.49, description: "Keep cords neat and tangle-free" },
    { id: 66, name: "Plant Watering Spike", category: "tools", price: 5.99, description: "Gradual water release for plants" },
    { id: 67, name: "Chip Clip Set - 6 Pack", category: "tools", price: 6.49, description: "Keep food fresh with bag clips" },
    { id: 68, name: "Measuring Spoons", category: "tools", price: 5.99, description: "Accurate spoon set for baking" },
    { id: 69, name: "Egg Separator", category: "tools", price: 3.99, description: "Easy egg white and yolk separation" },
    { id: 70, name: "Garlic Peeler", category: "tools", price: 4.49, description: "Quick garlic skin removal tool" },
    { id: 71, name: "Bag Sealer Clips", category: "tools", price: 5.49, description: "Airtight bag sealing clips" },
    { id: 72, name: "Lemon Squeezer", category: "tools", price: 6.99, description: "Extract maximum juice from citrus" },
    { id: 73, name: "Herb Stripper", category: "tools", price: 4.99, description: "Quick herb leaf removal tool" },
    { id: 74, name: "Pizza Cutter", category: "tools", price: 7.99, description: "Sharp rolling pizza cutting wheel" },
    { id: 75, name: "Ice Cream Scoop", category: "tools", price: 5.99, description: "Ergonomic ice cream serving scoop" },
    { id: 76, name: "Vegetable Peeler", category: "tools", price: 4.99, description: "Sharp ceramic blade peeler" },
    { id: 77, name: "Pastry Cutter Set", category: "tools", price: 8.99, description: "Various shapes for baking" },
    { id: 78, name: "Dough Scraper", category: "tools", price: 4.49, description: "Flexible dough handling tool" },
    { id: 79, name: "Jar Opener", category: "tools", price: 5.49, description: "Easy grip jar lid opener" },
    { id: 80, name: "Tea Strainer", category: "tools", price: 4.99, description: "Fine mesh tea leaf strainer" },

    { id: 81, name: "Phone Case - iPhone 14", category: "accessories", price: 9.99, description: "Protective case with custom design" },
    { id: 82, name: "Phone Case - Samsung S23", category: "accessories", price: 9.99, description: "Durable protection with style" },
    { id: 83, name: "Desk Calendar Stand", category: "accessories", price: 6.99, description: "Modern calendar display stand" },
    { id: 84, name: "Business Card Holder", category: "accessories", price: 5.99, description: "Professional card display case" },
    { id: 85, name: "Bookmark - Geometric", category: "accessories", price: 2.99, description: "Stylish geometric bookmark design" },
    { id: 86, name: "Badge Holder - Lanyard", category: "accessories", price: 4.49, description: "ID badge holder with clip" },
    { id: 87, name: "Desk Name Plate", category: "accessories", price: 7.99, description: "Customisable name plate for desk" },
    { id: 88, name: "Coaster Set - 4 Pack", category: "accessories", price: 8.99, description: "Protect surfaces with style" },
    { id: 89, name: "Glasses Stand", category: "accessories", price: 6.49, description: "Elegant eyewear display stand" },
    { id: 90, name: "Watch Stand", category: "accessories", price: 8.99, description: "Display your watches beautifully" },
    { id: 91, name: "Jewellery Holder - Tree", category: "accessories", price: 11.99, description: "Decorative tree for jewellery" },
    { id: 92, name: "Ring Holder - Dish", category: "accessories", price: 5.49, description: "Small dish for rings and trinkets" },
    { id: 93, name: "Earring Organiser", category: "accessories", price: 9.99, description: "Store multiple pairs neatly" },
    { id: 94, name: "Cufflink Box", category: "accessories", price: 7.99, description: "Elegant cufflink storage" },
    { id: 95, name: "Plant Markers - Set of 10", category: "accessories", price: 6.99, description: "Label your garden plants" },
    { id: 96, name: "Wine Glass Charms", category: "accessories", price: 5.99, description: "Identify glasses at parties" },
    { id: 97, name: "Napkin Rings - Set of 6", category: "accessories", price: 7.99, description: "Elegant table setting accessories" },
    { id: 98, name: "Tea Light Holder", category: "accessories", price: 6.49, description: "Decorative candle holder" },
    { id: 99, name: "Incense Holder", category: "accessories", price: 5.99, description: "Catch ash with style" },
    { id: 100, name: "Mini Planter Pot", category: "accessories", price: 4.99, description: "Small succulent planter" }
];
